### ISSUE TITLE
Constantly given ERR 8

### ISSUE THREAD

**Issue by ZeChild** [CZDanol/StreamDeck-DiscordVolumeMixer2#27]
I've had the plugin working since December 2023 however it has recently stopped working and throwing ERR 8. I've tried reinstalling from scratch and creating a new Discord app, I approve the authorisation popup I get in Discord and I continue to get ERR 8. Additionally every time Discord boots up I am prompted to authorise the app which I do each time to no avail.

**Comment by ctagliaferro** [comment]
I have had the same issue with no solution.

**Comment by bytorphoto** [comment]
Same issue. Had it working for months. Today, suddenly Err 8. I've checked all the settings, even updated to newer Streamdeck software to see if that helped, but no joy. Tried closing both, waiting 5 minutes after starting Discord before opening Streamdeck s/w, no joy. Tried reboot, no joy. Help. Was working perfectly yesterday, suddenly dead today, nothing changed between AFAIK.

**Comment by ctagliaferro** [comment]
> I have had the same issue with no solution.

Did all the same... tried update to Streamdeck software, tried uninstalling and reinstalling, tried starting Discord first, removing and reinstalling Discord Volume Mixer software, tried older version...  not sure what is going on.

**Comment by Watsune** [comment]
Have you guys found a solution for this?

**Comment by dWollmann** [comment]
Same issue here. Worked fine until a few days ago. Have tried everything

**Comment by CZDanol** [comment]
> > > Have you guys found a solution for this?
> > 
> > 
> > I certainly haven't
> 
> Me either... would love to hear if this is being worked on

It's not. If anyone figures what to do with it, feel free to create a PR.

**Comment by Cremery89** [comment]
> > > > > Have you guys found a solution for this?
> > > > 
> > > > 
> > > > I certainly haven't
> > > 
> > > 
> > > Me either... would love to hear if this is being worked on
> > 
> > 
> > It's not. If anyone figures what to do with it, feel free to create a PR.
> 
> Thanks for letting us know... hopefully we can figure it out. :)
_________

If you are having this issue you can
- UNINSTALL it from Stream deck. then got to https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/releases and download v2.0.1.8 
- TURN OFF AUTO UPDATE in stream deck once it is installed. 
- Delete the newly created profiles (as they are copies).

then if in a couple of months it happens again (like when stream deck does an update) repeat as auto update turned itself back on last stream deck update I did. 

I have only had issues on v2.0.1.9 - never had the issue on 8 so try reverting and home that helps.

**Comment by ctagliaferro** [comment]
> > > > > > Have you guys found a solution for this?
> > > > > 
> > > > > 
> > > > > I certainly haven't
> > > > 
> > > > 
> > > > Me either... would love to hear if this is being worked on
> > > 
> > > 
> > > It's not. If anyone figures what to do with it, feel free to create a PR.
> > 
> > 
> > Thanks for letting us know... hopefully we can figure it out. :)
> 
> If you are having this issue you can
> 
> * UNINSTALL it from Stream deck. then got to https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/releases and download v2.0.1.8
> * TURN OFF AUTO UPDATE in stream deck once it is installed.
> * Delete the newly created profiles (as they are copies).
> 
> then if in a couple of months it happens again (like when stream deck does an update) repeat as auto update turned itself back on last stream deck update I did.
> 
> I have only had issues on v2.0.1.9 - never had the issue on 8 so try reverting and home that helps.

Unfortunately did not work for me...  It looks like it downloads 2.0.1.7, even though I chose 2.0.1.8.  Tried closing both, opening Discord, opening StreamDeck after full load of Discord and choosing Authorize...  still shows Err 8.

**Comment by Cremery89** [comment]
> > > > > > > Have you guys found a solution for this?
> > > > > > 
> > > > > > 
> > > > > > I certainly haven't
> > > > > 
> > > > > 
> > > > > Me either... would love to hear if this is being worked on
> > > > 
> > > > 
> > > > It's not. If anyone figures what to do with it, feel free to create a PR.
> > > 
> > > 
> > > Thanks for letting us know... hopefully we can figure it out. :)
> > 
> > 
> > If you are having this issue you can
> > 
> > * UNINSTALL it from Stream deck. then got to https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/releases and download v2.0.1.8
> > * TURN OFF AUTO UPDATE in stream deck once it is installed.
> > * Delete the newly created profiles (as they are copies).
> > 
> > then if in a couple of months it happens again (like when stream deck does an update) repeat as auto update turned itself back on last stream deck update I did.
> > I have only had issues on v2.0.1.9 - never had the issue on 8 so try reverting and home that helps.
> 
> Unfortunately did not work for me... It looks like it downloads 2.0.1.7, even though I chose 2.0.1.8. Tried closing both, opening Discord, opening StreamDeck after full load of Discord and choosing Authorize... still shows Err 8.

hmmm so I looked and mine went 2.0.1.7 as well actually. It worked for me. I wounder if you try removing the authorization in Discord settings - Authorized Apps - Volume Mixer. Then close Discord and Stream Deck (even in the system tray), and relaunching?

**Comment by RonnieBlaze** [comment]
adding to the err 8 issue.   i get it every time i try to change the volume of anyone, i tried turn down/up someone and i saw the icon said disconnected and then picture came back if you keep spinning the dial it will disconnect again and then ERR 8.  so seems it might be a API rate limit getting trigger and then discord servers disconnect you.

**Comment by simonvandendyck** [comment]
Tried every solution describerd here and it's still now working.
Strange thing is that I don't see the plugin in the Authorized application section on Discord despite that I did allow it twice while prompted to

**Comment by Nekrozys** [comment]
Hi. I found this thread after I reinstalled Windows and encountered ERR 8 after following the setup instructions step by step despite it working fine before the reinstall. I noticed that Discord kept asking for authorization and every time it did, it did so twice (or the Discord window kinda blinked if I didn't click the Authorize button after a few seconds) but never seemed to properly register the authorization. 
I ended up "fixing" the issue by clicking the "Authorize" button immediately after it appeared after fully closing and reopening Discord. You can preview where the button will appear on your screen, restart discord and spam click the area. It might take you a few tries to nail the timing. 
A bit unusual but ever since I authorized the plugin as such, I haven't had any more error and the plugin is properly listed in the "Authorized application" section of Discord. 
I hope that helps a few people who have this issue.

**Comment by voidlesity** [comment]
So the basic fix that worked for me is remove the app from your authorized apps in discord then just reload discord (ctrl + r) and then get ready to quickly press authorize on the popup

hope this helps someone

**Comment by bytorphoto** [comment]
For me, it doesn't even get added to the Authorised Apps list, despite pressing the Authorise button both times.

I've tried removing the plugin, rebooting my pc, reinstalling the plugin, changing the app secret, etc. etc. etc. 

Every suggestion here, I've tried it and still get the legendary Err 8. At this point, I'm wondering if I'll just give up on this as currently, it's just taking up space for zero benefit (I know, not a lot of space, but still, it's space that could be better utilised). 

Unless anyone can find a definitive solution that works and lasts, I quit. 

It's gone on for far too long. Sorry to the Dev. I know this is free, but free and broken is still broken.

**Comment by ShadowsNight1000** [comment]
I suggest just using version V2.0.1.8 and turn off automatic updates if you're really unable to get it to work, that one works fine. If that version isn't working there's a very high chance there's something wrong with your dev portal.

**Comment by simonvandendyck** [comment]
> > I suggest just using version V2.0.1.8 and turn off automatic updates if you're really unable to get it to work, that one works fine. If that version isn't working there's a very high chance there's something wrong with your dev portal.
> 
> There is no 2.0.18. When I download 18, I get a version number of 17. Also, whatever version it actually is, that makes no difference.
> 
> Also, how could the portal be faullty when nothing changed between it working, and it not working? I even went to the extent of deleting the app from the dev portal and creating a new one, with the new ID, new secret, all the details correct from the installation instructions and it STILL doesn't work.

Did you try what I did recomment, to delete the directory AppData\Local\Elgato\Stream Deck ?
Could have it working without that and now it works like a charm even with latest version

**Comment by bytorphoto** [comment]
> Did you try what I did recomment, to delete the directory AppData\Local\Elgato\Stream Deck ?
> Could have it working without that and now it works like a charm even with latest version

So, you want me to completely purge everything from that folder and run it again? So I'd have to reinstall all the plugins, icon packs, profiles, etc.?

No. I actually wiped and reinstalled my whole Windows drive COMPLETELY about a month ago. Installed EVERYTHING from scratch, did NOT restore from a backup, and it has never worked since. I am not purging everything again because it's clear from the number of posts here that THE PLUGIN IS BROKEN!

**Comment by simonvandendyck** [comment]
No, there is a directory in it, specific to this plugin. Just remove this one.

**Comment by bytorphoto** [comment]
> No, there is a directory in it, specific to this plugin. Just remove this one.

Well, I did what you suggested, closed the Streamdeck, removed that folder, started the Streamdeck, installed the plugin and colour me surprised... NOTHING has changed. It's still broken, except now it flips between Err 2, Err 4 and Err 8 intermittently. Andy OTHER suggestions, I'm willing to listen.

**Comment by bytorphoto** [comment]
I even tried "2.0.18" or whatever that actually is, and 2.0.17. Same. Broken!

**Comment by ShadowsNight1000** [comment]
> There is no 2.0.18. When I download 18, I get a version number of 17. Also, whatever version it actually is, that makes no difference.

V2.0.1.8 just has a typo, you can change the version reported in elgato by changing the manifest.json if that makes you feel better.

> Also, how could the portal be faullty when nothing changed between it working, and it not working? I even went to the extent of deleting the app from the dev portal and creating a new one, with the new ID, new secret, all the details correct from the installation instructions and it STILL doesn't work.

I'm saying that your dev portal is probably set up WRONG if it isn't working with the EARLIER versions since YOU have CREATED A NEW ONE.
In the Installation tab make sure User install IS NOT ticked, Guild install IS ticked, and that you only have applications.commands in your install settings
In the OAuth2 tab make sure you have http://localhost:1337/callback

> I even tried "2.0.18" or whatever that actually is, and 2.0.17. Same. Broken!

These versions haven't changed since being published, you had it working "for months", the only thing that has changed will be on your end.

If you are using the streamdeck+, have the devportal setup correctly and wish to be able to push the dials to mute or scroll users. 
You'll need V2.0.1.9. It can work if you click both authorize prompts fast enough you've just got to be real quick, if you fail you can push ctrl+r in discord to try again. Good luck and god speed!

**Comment by bytorphoto** [comment]
Oh, guess what, I can follow instructions, and I HAVE done ALL that. And what you suggest to "fix" it is already done.

And when this issue came up first, NOTHING changed from one day to the next and it stopped working, OVERNIGHT. I went to bed and it was working, I woke up, and it WASN'T! IT IS NOT A FAULT AT MY END. It was working FOR MONTHS, then suddenly, OVERNIGHT, IT WASN'T!!!

I created a new dev portal page to PROVE that it wasn't my dev portal at fault. ALL the settings are exactly as detailed in the installation instructions and IT STILL DOESN'T WORK. IT'S BROKEN. Not my install, not my StreamDeck (not plus), not my dev portal set up. THE PLUGIN IS BROKEN. 

I keep seeing folk here say "Just remove it from the authorised apps and try again." IT DOESN'T APPEAR THERE FOR ME, DESPITE CLICKING **BOTH** AUTHORISATION PANELS EVERY TIME!!

If you got it working, well congratulations, but from the number of people I saw post about this suddenly breaking overnight, obviously DISCORD changed something in an update and it just hasn't been found/fixed in the plugin.

So stop telling me to do stuff I've already done, MULTIPLE times. Just 'cos it works for you, doesn't mean it's not broken, it just means you've been lucky to find a way that works for you.

I'm not blaming the author 'cos it could well be hidden somewhere they're missing. But I am getting annoyed at "well-meaning" people who constantly parrot the same stuff that I've already stated multiple times DOESN'T WORK FOR ME!! So stop saying "Well it works for me, yours' must be broken" and offer USEFUL assistance... or be quiet if you have nothing new to add.

**Comment by Nekrozys** [comment]
Skill issue.

**Comment by Nekrozys** [comment]
Quit like you said you would instead of yapping like a brat about volunteers trying to fix your shit. 
Ungrateful prick.

**Comment by bytorphoto** [comment]
> Quit like you said you would instead of yapping like a brat about volunteers trying to fix your shit. Ungrateful prick.

Trying to fix? From you? Piss off. If the "volunteers" had read my posts, they'd STOP REPEATING THE SAME SHIT OVER AND OVER AND OVER, claiming it's my problem. You're an arrogant wanker who has contributed nothing useful. Screw you and mind your damned business. If it works for you, great, but you can fuck off with your childish insults. Either contribute a solution that I haven't tried, or STFU!!!

**Comment by ShadowsNight1000** [comment]
@ctagliaferro I'd be happy to jump in a discord call and check your setup if you want, I've got a 100% success rate getting at least v2.0.1.8 working for people, some of them haven't even spoken English. I am just a guy who had the same problem but it usually only takes 5-15 min to sus out what's wrong, feel free to shoot me a message if I'm online.

**Comment by bytorphoto** [comment]
> @ctagliaferro I'd be happy to jump in a discord call and check your setup if you want, I've got a 100% success rate getting at least v2.0.1.8 working for people, some of them haven't even spoken English. I am just a guy who had the same problem but it usually only takes 5-15 min to sus out what's wrong, feel free to shoot me a message if I'm online.

And what about the rest of us?

**Comment by ShadowsNight1000** [comment]
I don't mind helping people who feel like their stuck against a wall, are respectful and believe they have already tried everything. Quite often it's just, in the multiple attempts to get it to work, something was missed and a second pair of eye's is all it takes. Other times people aren't sure how to uninstall the plugin before reinstalling it. The way that's been working for me is removing it from the plugin tab in the Elgato settings, follow the checks I suggested earlier and everything should work.

The only other piece of information that _might_ help, is just a theory of mine and is why I said

> It can work if you click both authorize prompts fast enough you've just got to be real quick, if you fail you can push ctrl+r in discord to try again. Good luck and god speed!

With the latest version I believe you only have 3 seconds to accept both authentication prompts, for some people, discord takes a while to reopen after the first prompt and it can be real hard to do that, or impossible in some cases. With the older version I believe you have 10 seconds and it's a lot easier to get that to work. Pure speculation though until I figure out how to test the changes in the library.

It probably won't work for you though, since you didn't think any of [this](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/issues/27#issuecomment-2308602140) or [this](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/issues/27#issuecomment-2311359353) was "useful", it's possible nothing will help you. This is more for everyone else who comes here.

**Comment by bytorphoto** [comment]
@ShadowsNight1000 FYI I was perfectly respectful until people just started parroting the same instructions that I'd tried, time and time again, and that I'd even explained, multiple times, that I'd tried and explained that none of it worked.

I then got insulted [here](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/issues/27#issuecomment-2312865690) and when I responded with the same energy I received, I was then insulted again by the same user [here](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/issues/27#issuecomment-2312940107) so, yet again I returned the same energy I'd received.

Now, I didn't insult YOU, or anyone until I was first insulted/abused. In fact, I didn't insult ANYONE other than that one poster who added zero to my question/discussion beyond abuse.

So, if you want to not do the Discord call and see if I DID make an honest mistake, then that's up to you. But I have only responded in kind to the insults I received.

I've been in tech support for about 40 years, I'm not some noob that needs to be talked down to, and I will NOT take insults lying down.

So, do as you wish, but don't blame me for escalating. I note you didn't get on at the user who insulted me twice. 

> I don't mind helping people who feel like their stuck against a wall, are respectful and believe they have already tried everything.

Well, guess what... I fit all those criteria. I WAS respectful until I was abused. I never abused or insulted you. I have tried EVERYTHING that was in the install instructions, and that was suggested here, INCLUDING the two posts you linked, MULTIPLE TIMES as previously stated, but nobody seems to be able to understand.

Fine, if you want to feel disrespected, that's up to you, but that wasn't and isn't the case. So make a decision. Deal with the abusive user, or whatever. If you cannot add anything constructive, then don't add anything. That would be respectful behaviour.

**Comment by CZDanol** [comment]
Sorry guys, I am fully consumed by my dayjob programming-wise and don't have time/energy/mental capacity trying to deal with this. PRs are welcome. I feel like discussing under this topic went quite sideways, so I'm closing this because I'm tired reading it.
